{% set name = "yaqd-dwyer" %}
{% set version = "2023.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 87863d81c90180fc03da65e094c86fc1c5708525cf0ed42e3d074096c2b7693e

build:
  entry_points:
    - yaqd-dwyer-16b = yaqd_dwyer._dwyer_16b:Dwyer16B.main
    - yaqd-dwyer-16c = yaqd_dwyer._dwyer_16c:Dwyer16C.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7
  run:
    - minimalmodbus
    - pyserial
    - python >=3.7
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_dwyer
  commands:
    - pip check
    - yaqd-dwyer-16b --help
    - yaqd-dwyer-16c --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Dwyer instruments and controllers
  dev_url: https://github.com/yaq-project/yaqd-dwyer
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
